<a href="https://colab.research.google.com/github/emersonpalacio/APIRest/blob/main/Copia_de_Te_damos_la_bienvenida_a_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p><img alt="Colaboratory logo" height="45px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

<h1>¿Qué es Colaboratory?</h1>

Colaboratory, también llamado Colab, te permite escribir y ejecutar código de Python en un navegador, con las siguientes particularidades:
- Sin configuración requerida
- Acceso gratuito a GPU
- Facilidad para compartir

Seas <strong>estudiante</strong>, <strong>científico de datos</strong> o <strong>investigador de IA</strong>, Colab facilita tu trabajo. Mira <a href="https://www.youtube.com/watch?v=inN8seMm7UI">este video introductorio sobre Colab</a> para obtener más información, o bien comienza a usarlo más abajo.

## <strong>Introducción</strong>

El documento que estás leyendo no es una página web estática, sino un entorno interactivo denominado <strong>notebook de Colab</strong>, que permite escribir y ejecutar código.

Por ejemplo, esta es una <strong>celda de código</strong> con una secuencia de comandos Python corta que calcula un valor, lo almacena en una variable y devuelve el resultado:

In [ ]:
seconds_in_a_day = 24 * 60 * 60
seconds_in_a_day

86400

A fin de ejecutar el código en la celda anterior, haz clic en él para seleccionarlo y luego presiona el botón de reproducción ubicado a la izquierda del código o usa la combinación de teclas "Command/Ctrl + Intro". Para editar el código, solo haz clic en la celda y comienza a editar.

Las variables que defines en una celda pueden usarse en otras:

In [ ]:
seconds_in_a_week = 7 * seconds_in_a_day
seconds_in_a_week

604800

Los notebooks de Colab te permiten combinar <strong>código ejecutable</strong> y <strong>texto enriquecido</strong> en un único documento, junto con <strong>imágenes</strong>, <strong>HTML</strong>, <strong>LaTeX</strong> y mucho más. Los notebooks que crees en Colab se almacenan en tu cuenta de Google Drive. Puedes compartir fácilmente los notebooks de Colab con amigos o compañeros de trabajo para que realicen comentarios o los editen. Si quieres obtener más información, consulta la <a href="/notebooks/basic_features_overview.ipynb">Descripción general de Colab</a>. Para crear un nuevo notebook de Colab, ve al menú Archivo que aparece más arriba o usa este vínculo: <a href="http://colab.research.google.com#create=true">crear un nuevo notebook de Colab</a>.

Los notebooks de Colab son notebooks de Jupyter que aloja Colab. Para obtener más información sobre el proyecto Jupyter, visita <a href="https://www.jupyter.org">jupyter.org</a>.

## Ciencia de datos

Con Colab, puedes aprovechar por completo las bibliotecas más populares de Python para analizar y visualizar datos. La celda de código que se incluye a continuación usa <strong>NumPy</strong> para generar algunos datos aleatorios y <strong>matplotlib</strong> para visualizarlos. Para editar el código, haz clic en la celda y comienza a editar.

In [39]:
#@title nompy
import numpy as np

lista =[1,2,3,4,5,6,7,8]
print(lista)
print('----------------------------------------')

arreglo = np.array(lista)
print(arreglo)
print('----------------------------------------')

miMatriz =[[1,2,3],[4,5,6]]
print(miMatriz)
print('----------------------------------------')

matriz = np.array(miMatriz)
print(matriz)
print('----------------------------------------')

a=np.arange(1,12)
print(a)
print('----------------------------------------')

a=np.arange(0,20,2)
print(a)
print('----------------------------------------')

a0= np.zeros(5)
print(a0)
print('----------------------------------------')

m0=np.zeros((3,5))
print(m0)
print('----------------------------------------')

a1=np.ones(5)
print(a1)
print('----------------------------------------')

m1 = np.ones((3,5))
print(m1)
print('----------------------------------------')

a2=np.linspace(0,10,4)
print(a2)
print('----------------------------------------')

a2 =np.linspace(0,10,7)
print(a2)
print('----------------------------------------')

m2 = np.eye(5)
print(m2)
print('----------------------------------------')

ra = np.random.rand(5)
print(ra)
print('----------------------------------------')

m3 = np.random.rand(3,5)
print(m3)
print('----------------------------------------')

a4 = np.random.randn(5)
print(a4)
print('----------------------------------------')
a4 = np.random.randn(3,4)
print(a4)
print('----------------------------------------')

a5 = np.random.randint(3,15,5)
print(a5)
print('-----------------------------------------')

m5 = np.random.randint(3,15,(3,5))
print(a5)
print('----------------------------------------')

print(a5.shape)
print(m5.shape)
print('----------------------------------------')

a6 = np.random.randint(0,100,10)
print(a6)
print(a6.shape)
print('----------------------------------------')

m7=a6.reshape(2,5)
print(m7)
print('----------------------------------------')

m8=a6.reshape(2,-1)
print(m8)
print('----------------------------------------')

m9= a6.reshape(-1,2)
print(m9)
print('----------------------------------------')

print(m9.max())
print('----------------------------------------')
print('----------------------------------------')
print(m9.min())

print('----------------------------------------')

print(m9.argmax())
print('----------------------------------------')
print(m9.argmin())

print('----------------------------------------')





[1, 2, 3, 4, 5, 6, 7, 8]
----------------------------------------
[1 2 3 4 5 6 7 8]
----------------------------------------
[[1, 2, 3], [4, 5, 6]]
----------------------------------------
[[1 2 3]
 [4 5 6]]
----------------------------------------
[ 1  2  3  4  5  6  7  8  9 10 11]
----------------------------------------
[ 0  2  4  6  8 10 12 14 16 18]
----------------------------------------
[0. 0. 0. 0. 0.]
----------------------------------------
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
----------------------------------------
[1. 1. 1. 1. 1.]
----------------------------------------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
----------------------------------------
[ 0.          3.33333333  6.66666667 10.        ]
----------------------------------------
[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]
----------------------------------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0

AttributeError: ignored

Puedes importar datos propios a notebooks de Colab desde tu cuenta de Google Drive &#40;incluso desde hojas de cálculos&#41;, GitHub y muchas otras fuentes. Para obtener más información acerca de la importación de datos y cómo puede usarse Colab para fines relacionados con la ciencia de datos, consulta los vínculos de <a href="#working-with-data">Cómo trabajar con datos</a>.

## Aprendizaje automático

Colab te permite importar un conjunto de datos de imágenes, entrenar un clasificador de imágenes en él y evaluar el modelo con solo <a href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb">unas pocas líneas de código</a>. Los notebooks de Colab ejecutan código en los servidores alojados en la nube de Google, lo que significa que puedes aprovechar al máximo el hardware de Google, incluidas las <a href="#using-accelerated-hardware">GPU y TPU</a>, independientemente de la potencia de tu máquina. Lo único que necesitas es un navegador.

# Sección nueva

Entre los usos que se la da a Colab en la comunidad de aprendizaje automático, se encuentran los siguientes:
- Introducción a TensorFlow
- Desarrollo y entrenamiento de redes neuronales
- Experimentación con TPU
- Diseminación de investigación de IA
- Creación de instructivos

Para ver notebooks de Colab de ejemplo que muestran los usos del aprendizaje automático, consulta los <a href="#machine-learning-examples">ejemplos</a> que se incluyen a continuación.

## Más recursos

### Cómo trabajar con notebooks en Colab
- [Descripción general de Colaboratory](/notebooks/basic_features_overview.ipynb)
- [Guía para usar Markdown](/notebooks/markdown_guide.ipynb)
- [Cómo importar bibliotecas y luego instalar dependencias](/notebooks/snippets/importing_libraries.ipynb)
- [Cómo guardar y cargar notebooks en GitHub](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb)
- [Formularios interactivos](/notebooks/forms.ipynb)
- [Widgets interactivos](/notebooks/widgets.ipynb)
- <img src="/img/new.png" height="20px" align="left" hspace="4px" alt="New"></img>
 [TensorFlow 2 en Colab](/notebooks/tensorflow_version.ipynb)

<a name="working-with-data"></a>
### Cómo trabajar con datos
- [Cómo cargar datos: Drive, Hojas de cálculo y Google Cloud Storage](/notebooks/io.ipynb) 
- [Gráficos: visualización de datos](/notebooks/charts.ipynb)
- [Cómo comenzar a usar BigQuery](/notebooks/bigquery.ipynb)

### Curso intensivo de aprendizaje automático
Estos son algunos de los notebooks del curso de aprendizaje automático en línea de Google. Para obtener más información, consulta el <a href="https://developers.google.com/machine-learning/crash-course/">sitio web del curso completo</a>.
- [Introducción a Pandas](/notebooks/mlcc/intro_to_pandas.ipynb)
- [Conceptos de TensorFlow](/notebooks/mlcc/tensorflow_programming_concepts.ipynb)
- [Primeros pasos con TensorFlow](/notebooks/mlcc/first_steps_with_tensor_flow.ipynb)
- [Introducción a las redes neuronales](/notebooks/mlcc/intro_to_neural_nets.ipynb)
- [Introducción a los datos dispersos y las incorporaciones](/notebooks/mlcc/intro_to_sparse_data_and_embeddings.ipynb)

<a name="using-accelerated-hardware"></a>
### Uso de aceleración de hardware
- [TensorFlow con GPU](/notebooks/gpu.ipynb)
- [TensorFlow con TPU](/notebooks/tpu.ipynb)

<a name="machine-learning-examples"></a>

## Ejemplos de aprendizaje automático

Para ver ejemplos de extremo a extremo de los análisis de aprendizaje automático interactivo que Colaboratory permite realizar, consulta estos instructivos con modelos de <a href="https://tfhub.dev">TensorFlow Hub</a>.

Algunos ejemplos destacados son los siguientes:

- <a href="https://tensorflow.org/hub/tutorials/tf2_image_retraining">Reentrenamiento de un clasificador de imágenes</a>: compila un modelo de Keras sobre un clasificador de imágenes previamente entrenado para distinguir flores.
- <a href="https://tensorflow.org/hub/tutorials/tf2_text_classification">Clasificación de texto</a>: clasifica opiniones sobre películas de IMDB como <em>positivas</em> o <em>negativas</em>.
- <a href="https://tensorflow.org/hub/tutorials/tf2_arbitrary_image_stylization">Transferencia de estilos</a>: usa el aprendizaje profundo para transferir el estilo de una imagen a otra.
- <a href="https://tensorflow.org/hub/tutorials/retrieval_with_tf_hub_universal_encoder_qa">Codificador universal de oraciones en varios idiomas para preguntas y respuestas</a>: usa un modelo de aprendizaje automático para responder preguntas del conjunto de datos SQuAD.
- <a href="https://tensorflow.org/hub/tutorials/tweening_conv3d">Interpolación de videos</a>: predice lo que sucedió en un video entre el primer y el último fotograma.
